pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prIssueCheck: true
    - id: swiftlint
      config:
        projectFolder: Stampede
    - id: unit-tests-xcode
      config:
        projectFolder: Stampede
        scheme: Stampede
        project: Stampede
        xcodeVersion: Xcode-beta.app
  notifications:
    all:
      - slack-stampede-dev
      - prcomment
pullrequestedit:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
branches:
  main:
    tasks:
      - id: app-build-xcode
        config:
          projectFolder: Stampede
          scheme: Stampede
          project: Stampede
          xcodeVersion: Xcode-beta.app
          productName: Stampede
          infoPlist: Stampede/Info.plist
releases:
  published:
    tasks:
      - id: release-notes
