config:
  productName: Stampede
  projectFolder: Stampede
  xcodeVersion: Xcode-beta.app
  simulator: iPhone 13
  project: Stampede
  scheme: Stampede
  infoPlist: Stampede/Info.plist
pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prIssueCheck: true
    - id: swiftlint
    - id: unit-tests-xcode
    - id: ui-tests-xcode
      config:
        scheme: StampedeUITests
    - id: lines-of-code
      config:
        excludeFolders: HouseKit
  notifications:
    all:
      - id: prcomment
pullrequestedit:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
branches:
  main:
    tasks:
      - id: app-build-xcode
        config:
      - id: catalyst-build-xcode
      - id: lines-of-code
        config:
          excludeFolders: HouseKit
      - id: swiftlint
      - id: unit-tests-xcode
      - id: ui-tests-xcode
        config:
          scheme: StampedeUITests
    notifications:
      all:
        - id: slack-stampede-dev
releases:
  published:
    tasks:
      - id: release-notes
      - id: app-build-xcode
      - id: catalyst-build-xcode
    notifications:
      all:
        - id: slack-stampede-dev
