pullrequests:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
        prIssueCheck: true
    - id: swiftlint
      config:
        projectFolder: Stampede
    - id: unit-tests-xcode
      config:
        projectFolder: Stampede
        scheme: Stampede
        project: Stampede
        xcodeVersion: Xcode.app
        simulator: iPhone 11
    - id: ui-tests-xcode
      config:
        projectFolder: Stampede
        scheme: StampedeUITests
        project: Stampede
        xcodeVersion: Xcode.app
        simulator: iPhone 11
    - id: lines-of-code
      config:
        excludeFolders: HouseKit
  notifications:
    all:
      - id: prcomment
pullrequestedit:
  tasks:
    - id: pr-standards
      config:
        prMilestoneCheck: true
branches:
  main:
    tasks:
      - id: app-build-xcode
        config:
          projectFolder: Stampede
          scheme: Stampede
          project: Stampede
          xcodeVersion: Xcode.app
          productName: Stampede
          infoPlist: Stampede/Info.plist
      - id: catalyst-build-xcode
        config:
          projectFolder: Stampede
          scheme: Stampede
          project: Stampede
          infoPlist: Stampede/Info.plist
          xcodeVersion: Xcode.app
      - id: lines-of-code
        config:
          excludeFolders: HouseKit
      - id: swiftlint
        config:
          projectFolder: Stampede
      - id: unit-tests-xcode
        config:
          projectFolder: Stampede
          scheme: Stampede
          project: Stampede
          xcodeVersion: Xcode.app
          simulator: iPhone 11
      - id: ui-tests-xcode
        config:
          projectFolder: Stampede
          scheme: StampedeUITests
          project: Stampede
          xcodeVersion: Xcode.app
          simulator: iPhone 11
    notifications:
      all:
        - id: slack-stampede-dev
releases:
  published:
    tasks:
      - id: release-notes
